# Estamos usando Java 17 como base para practicar 
FROM openjdk:17-jdk-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Por ahora solo mantenemos el contenedor vivo
CMD ["sleep", "infinity"]
